import 'dart:ui';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage extends ChangeNotifier {
  static const String _storageKey = 'app_selected_language';
  static const List<String> supportedLanguages = ['English', 'Kannada', 'Telugu', 'Tamil', 'Hindi'];

  static final AppLanguage _instance = AppLanguage._internal();

  factory AppLanguage() => _instance;

  AppLanguage._internal();

  String _language = 'English';

  String get language => _language;

  Locale get locale => _localeFor(_language);

  static List<Locale> get supportedLocales => const [
    Locale('en'),
    Locale('kn'),
    Locale('te'),
    Locale('ta'),
    Locale('hi'),
  ];

  static Locale _localeFor(String language) {
    switch (language) {
      case 'Kannada':
        return const Locale('kn');
      case 'Telugu':
        return const Locale('te');
      case 'Tamil':
        return const Locale('ta');
      case 'Hindi':
        return const Locale('hi');
      case 'English':
      default:
        return const Locale('en');
    }
  }

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final stored = prefs.getString(_storageKey) ?? 'English';
    if (supportedLanguages.contains(stored)) {
      _language = stored;
    } else {
      _language = 'English';
    }
    notifyListeners();
  }

  Future<void> setLanguage(String language) async {
    final next = supportedLanguages.contains(language) ? language : 'English';
    if (_language == next) return;
    _language = next;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_storageKey, next);
    notifyListeners();
  }

  String translate(String key) {
    final map = _translations[_language] ?? _translations['English'] ?? {};
    return map[key] ?? _translations['English']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'checking_whos_here': "Checking who's here...",
      'no_face_detected': 'No face detected',
      'no_matching_patient_found': 'No matching patient found',
      'ready_to_scan': 'Ready to scan',
      'people_i_ve_talked_to': 'People I’ve talked to',
      'no_recent_memories_yet': 'No recent memories yet.',
      'scan_using_camera_icon': 'Scan using camera icon',
      'ask_caregiver_to_save_profile': 'Ask caregiver to save patient profile first',
      'unknown_person_detected': 'Unknown person detected',
      'patient_not_enrolled': 'Patient not enrolled yet. Caregiver must save profile before scan.',
      'patient_mode': 'Patient mode',
      'games': 'Games',
      'relationship': 'Relationship',
      'none': 'None',
      'usage_reminder_title': 'Usage reminder',
      'usage_reminder_message': 'You are using this application.',
      'recent_memories': 'Recent memories',
      'conversation_capture_active': 'Conversation capture is active.',
      'glasses_recording': 'Your glasses are recording this conversation.',
      'last_conversation': 'Last conversation',
      'no_previous_conversation_found': 'No previous conversation found.',
      'start_conversation': 'Start Conversation',
      'stop_recording': 'Stop recording',
      'saving': 'Saving...',
      'capturing_conversation': 'Capturing conversation...',
      'waiting_for_speech': 'Waiting for speech...',
      'listening': 'Listening...',
      'language': 'Language',
      'recognized': 'Recognized',
      'exit_patient_mode_question': 'Exit patient mode?',
      'exit_patient_mode_message': 'This closes the patient screen and returns to caregiver sign-in.',
      'cancel': 'Cancel',
      'exit': 'Exit',
      'back_to_home': 'Back to Home',
      'try_again': 'Please try again.',
      'speaking_last_summary': 'Speaking last summary...',
      'ready_to_capture': 'Ready to capture your conversation.',
      'starting_recording': 'Starting recording...',
      'recording_not_started': 'Recording not started.',
      'microphone_required': 'Microphone permission is required to record your conversation.',
      'no_speech_detected': 'No speech detected for 5 seconds. Stopping capture...',
      'conversation_saved_success': 'Conversation saved successfully. Returning home...',
      'conversation_save_failed': 'Failed to save conversation. You can try again from home.',
      'people_talked_to': 'People I’ve talked to',
      'game_sequence_memory': 'Sequence Memory',
      'game_image_matching': 'Image Matching',
      'game_missing_card_memory': 'Missing Card Memory',
      'game_daily_routine_recall': 'Daily Routine Recall',
      'routine_wake_up': 'Wake Up',
      'routine_brush': 'Brush',
      'routine_breakfast': 'Breakfast',
      'routine_medicine': 'Medicine',
      'routine_walk': 'Walk',
      'routine_rest': 'Rest',
      'game_start': 'START',
      'sequence_observe': 'Remember where each number is located.\nOpen the numbers in order from 1 to {number}.',
      'sequence_find': 'Find {number}',
      'sequence_completed': 'Sequence completed!',
      'game_try_again': 'Try again',
      'image_observe': 'Remember the card locations and the matching pairs.',
      'image_open_pair': 'Open one card, then another card.',
      'image_match': 'Match!',
      'image_not_match': 'Not a match',
      'game_great_job': 'Great job!',
      'missing_observe': 'Remember all the cards.\nOne card will be missing.',
      'missing_question': 'Which card is missing?',
      'game_correct': 'Correct!',
      'routine_observe': 'Observe the routine below carefully.',
      'routine_after': 'What comes after {activity}?',
      'routine_before': 'What comes before {activity}?',
      'routine_first': 'What is the first activity?',
      'routine_not_quite': 'Not quite',
      'routine_next_question': 'Next question',
      'game_unavailable': 'Game unavailable',
      'game_completed': 'Game completed',
      'game_label': 'Game: {game}',
      'accuracy_label': 'Accuracy: {accuracy}%',
      'correct_attempts_label': 'Correct: {correct}/{attempts} attempts',
      'errors_label': 'Errors: {errors}',
      'attempts_label': 'Attempts: {attempts}',
      'difficulty_label': 'Difficulty: Level {level}',
      'sending_result': 'Sending result to caregiver...',
      'score_save_failed': 'Could not send this result to your caregiver. Check the connection and retry.',
      'retry': 'Retry',
      'result_sent': 'Result sent to caregiver.',
      'back_to_games': 'Back to games',
      'improvements_patient_title': 'Patient Improvements',
      'improvements_load_error': 'Could not load game results',
      'caregiver_sign_in_required': 'Caregiver sign-in is required to load results.',
      'improvements_performance': 'Gaming Performance',
      'improvements_history': 'Game History',
      'improvements_empty': 'No game results recorded yet.',
      'improvements_correct_total': 'Correct {correct}/{total}',
      'improvements_played_times': 'Played: {count} times',
      'improvements_latest': 'Latest {score}%',
      'session_expired': 'Your session expired. Please sign in again.',
    },
    'Kannada': {
      'checking_whos_here': 'ಯಾರು ಇಲ್ಲಿದ್ದಾರೆ ಎಂದು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
      'no_face_detected': 'ಮುಖ ಕಂಡುಬಂದಿಲ್ಲ',
      'no_matching_patient_found': 'ಹೊಂದಾಣಿಕೆಯ ರೋಗಿ ಕಂಡುಬಂದಿಲ್ಲ',
      'ready_to_scan': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಸಿದ್ಧವಾಗಿದೆ',
      'people_i_ve_talked_to': 'ನಾನು ಮಾತನಾಡಿದ ಜನರು',
      'no_recent_memories_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಇತ್ತೀಚಿನ ನೆನಪುಗಳಿಲ್ಲ.',
      'scan_using_camera_icon': 'ಕ್ಯಾಮೆರಾ ಐಕಾನ್ ಬಳಸಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'ask_caregiver_to_save_profile': 'ಪೇಷಕರು ರೋಗಿಯ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಸೇವ್ ಮಾಡಬೇಕು',
      'unknown_person_detected': 'ಅಪರಿಚಿತ ವ್ಯಕ್ತಿ ಪತ್ತೆಯಾಗಿದೆ',
      'patient_not_enrolled': 'ರೋಗಿಯನ್ನು ನೋಂದಾಯಿಸಿಲ್ಲ. ಸ್ಕ್ಯಾನ್ ಮಾಡುವ ಮೊದಲು ಕೇರ್‌ಗಾರರು ಪ್ರೊಫೈಲ್ ಸೇವ್ ಮಾಡಬೇಕು.',
      'patient_mode': 'ರೋಗಿ ಮೋಡ್',
      'games': 'ಆಟಗಳು',
      'relationship': 'ಸಂಬಂಧ',
      'none': 'ಯಾವುದೂ ಇಲ್ಲ',
      'usage_reminder_title': 'ಬಳಕೆ ಜ್ಞಾಪನೆ',
      'usage_reminder_message': 'ನೀವು ಈ ಅಪ್ಲಿಕೇಶನ್ ಬಳಸುತ್ತಿದ್ದೀರಿ.',
      'recent_memories': 'ಇತ್ತೀಚಿನ ನೆನಪುಗಳು',
      'conversation_capture_active': 'ಮಾತುಕಥೆ ಸೆರೆಹಿಡಿಯುವಿಕೆ ಸಕ್ರಿಯವಾಗಿದೆ.',
      'glasses_recording': 'ನಿಮ್ಮ ಕಣ್ಣಡಿಯಲ್ಲಿ ಈ ಸಂಭಾಷಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ.',
      'last_conversation': 'ಕೊನೆಯ ಸಂಭಾಷಣೆ',
      'no_previous_conversation_found': 'ಹಿಂದಿನ ಸಂಭಾಷಣೆ ಕಂಡುಬಂದಿಲ್ಲ.',
      'start_conversation': 'ಸಂಭಾಷಣೆ शुरूಮಾಡಿ',
      'stop_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
      'saving': 'ಸೇವ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      'capturing_conversation': 'ಸಂಭಾಷಣೆಯನ್ನು ಸೆರೆಹಿಡಿಯಲಾಗುತ್ತಿದೆ...',
      'waiting_for_speech': 'ಮಾತು ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ...',
      'listening': 'ಕೇಳಲಾಗುತ್ತಿದೆ...',
      'language': 'ಭಾಷೆ',
      'recognized': 'ಗುರುತಿಸಲಾಗಿದೆ',
      'exit_patient_mode_question': 'ರೋಗಿ ಮೋಡ್‌ನಿಂದ ನಿರ್ಗಮಿಸುವುದೇ?',
      'exit_patient_mode_message': 'ಇದು ರೋಗಿ ಪರದೆಯನ್ನು ಮುಚ್ಚಿ ಕೇರ್‌ಗಾರರ ಸೈನ್-ಇನ್‌ಗೆ തിരികೆ ತರುತ್ತದೆ.',
      'cancel': 'ರದ್ದುಮಾಡು',
      'exit': 'ನಿರ್ಗಮಿಸಿ',
      'back_to_home': 'ಮನೆಗೆ ಹಿಂತಿರುಗಿ',
      'try_again': 'ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'speaking_last_summary': 'ಕೊನೆಯ ಸಾರಾಂಶವನ್ನು ಹೇಳಲಾಗುತ್ತಿದೆ...',
      'ready_to_capture': 'ನಿಮ್ಮ ಸಂಭಾಷಣೆಯನ್ನು ಸೆರೆಹಿಡಿಯಲು ಸಿದ್ಧವಾಗಿದೆ.',
      'starting_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ...',
      'recording_not_started': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭವಾಗಲಿಲ್ಲ.',
      'microphone_required': 'ನಿಮ್ಮ ಸಂಭಾಷಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಲು ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
      'no_speech_detected': '5 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಮಾತನಾಡು ಕಂಡುಬಂದಿಲ್ಲ. ಸೆರೆಹಿಡಿಯುವುದನ್ನು ನಿಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
      'conversation_saved_success': 'ಸಂಭಾಷಣೆ 저장되었습니다. ಮನೆಗೆ ಮರಳಲಾಗುತ್ತಿದೆ...',
      'conversation_save_failed': 'ಸಂಭಾಷಣೆಯನ್ನು ಉಳಿಸಲು ವಿಫಲವಾಯಿತು. ನೀವು المنزلದಿಂದ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಬಹುದು.',
      'people_talked_to': 'ನಾನು ಮಾತನಾಡಿದ ಜನರು',
      'game_sequence_memory': 'ಕ್ರಮ ಸ್ಮರಣೆ',
      'game_image_matching': 'ಚಿತ್ರ ಹೊಂದಾಣಿಕೆ',
      'game_missing_card_memory': 'ಕಾಣೆಯಾದ ಕಾರ್ಡ್ ಸ್ಮರಣೆ',
      'game_daily_routine_recall': 'ದೈನಂದಿನ ಕ್ರಮದ ನೆನಪು',
      'routine_wake_up': 'ಎಚ್ಚರಗೊಳ್ಳಿ',
      'routine_brush': 'ಹಲ್ಲು ತೊಳೆಯಿರಿ',
      'routine_breakfast': 'ಉಪಾಹಾರ',
      'routine_medicine': 'ಔಷಧಿ',
      'routine_walk': 'ನಡಿಗೆ',
      'routine_rest': 'ವಿಶ್ರಾಂತಿ',
      'game_start': 'ಪ್ರಾರಂಭಿಸಿ',
      'sequence_observe': 'ಪ್ರತಿ ಸಂಖ್ಯೆಯ ಸ್ಥಾನವನ್ನು ನೆನಪಿಡಿ.\n1 ರಿಂದ {number} ರವರೆಗೆ ಕ್ರಮವಾಗಿ ತೆರೆಯಿರಿ.',
      'sequence_find': '{number} ಅನ್ನು ಹುಡುಕಿ',
      'sequence_completed': 'ಕ್ರಮ ಪೂರ್ಣಗೊಂಡಿದೆ!',
      'game_try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'image_observe': 'ಕಾರ್ಡ್‌ಗಳ ಸ್ಥಾನ ಮತ್ತು ಹೊಂದಾಣಿಕೆಯ ಜೋಡಿಗಳನ್ನು ನೆನಪಿಡಿ.',
      'image_open_pair': 'ಒಂದು ಕಾರ್ಡ್ ತೆರೆಯಿರಿ, ನಂತರ ಮತ್ತೊಂದು ಕಾರ್ಡ್ ತೆರೆಯಿರಿ.',
      'image_match': 'ಹೊಂದಾಣಿಕೆಯಾಗಿದೆ!',
      'image_not_match': 'ಹೊಂದಾಣಿಕೆಯಾಗಿಲ್ಲ',
      'game_great_job': 'ಅತ್ಯುತ್ತಮ!',
      'missing_observe': 'ಎಲ್ಲಾ ಕಾರ್ಡ್‌ಗಳನ್ನು ನೆನಪಿಡಿ.\nಒಂದು ಕಾರ್ಡ್ ಕಾಣೆಯಾಗುತ್ತದೆ.',
      'missing_question': 'ಯಾವ ಕಾರ್ಡ್ ಕಾಣೆಯಾಗಿದೆ?',
      'game_correct': 'ಸರಿಯಾಗಿದೆ!',
      'routine_observe': 'ಕೆಳಗಿನ ದಿನಚರಿಯನ್ನು ಗಮನದಿಂದ ನೋಡಿ.',
      'routine_after': '{activity} ನಂತರ ಏನು ಬರುತ್ತದೆ?',
      'routine_before': '{activity} ಮೊದಲು ಏನು ಬರುತ್ತದೆ?',
      'routine_first': 'ಮೊದಲ ಚಟುವಟಿಕೆ ಯಾವುದು?',
      'routine_not_quite': 'ಸರಿಯಾಗಿಲ್ಲ',
      'routine_next_question': 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
      'game_unavailable': 'ಆಟ ಲಭ್ಯವಿಲ್ಲ',
      'game_completed': 'ಆಟ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'game_label': 'ಆಟ: {game}',
      'accuracy_label': 'ನಿಖರತೆ: {accuracy}%',
      'correct_attempts_label': 'ಸರಿ: {correct}/{attempts} ಪ್ರಯತ್ನಗಳು',
      'errors_label': 'ತಪ್ಪುಗಳು: {errors}',
      'attempts_label': 'ಪ್ರಯತ್ನಗಳು: {attempts}',
      'difficulty_label': 'ಕಷ್ಟದ ಮಟ್ಟ: {level}',
      'sending_result': 'ಫಲಿತಾಂಶವನ್ನು ಕೇರ್‌ಗಿವರ್‌ಗೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
      'score_save_failed': 'ಫಲಿತಾಂಶ ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ. ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'result_sent': 'ಫಲಿತಾಂಶ ಕೇರ್‌ಗಿವರ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.',
      'back_to_games': 'ಆಟಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
      'improvements_patient_title': 'ರೋಗಿಯ ಪ್ರಗತಿ',
      'improvements_load_error': 'ಆಟದ ಫಲಿತಾಂಶಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ',
      'caregiver_sign_in_required': 'ಫಲಿತಾಂಶಗಳನ್ನು ಪಡೆಯಲು ಕೇರ್‌ಗಿವರ್ ಸೈನ್-ಇನ್ ಅಗತ್ಯವಿದೆ.',
      'improvements_performance': 'ಆಟದ ಪ್ರದರ್ಶನ',
      'improvements_history': 'ಆಟದ ಇತಿಹಾಸ',
      'improvements_empty': 'ಇನ್ನೂ ಆಟದ ಫಲಿತಾಂಶಗಳಿಲ್ಲ.',
      'improvements_correct_total': 'ಸರಿ {correct}/{total}',
      'improvements_played_times': '{count} ಬಾರಿ ಆಡಲಾಗಿದೆ',
      'improvements_latest': 'ಇತ್ತೀಚಿನದು {score}%',
      'session_expired': 'ನಿಮ್ಮ ಸೀಷನ್ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    },
    'Telugu': {
      'checking_whos_here': 'ఎవరు ఇక్కడ ఉన్నారు అని పరిశీలిస్తున్నాం...',
      'no_face_detected': 'ముఖం కనబడలేదు',
      'no_matching_patient_found': 'పోలిక ఉన్న పేషెంట్ కనబడలేదు',
      'ready_to_scan': 'స్కాన్‌కి సిద్ధంగా ఉంది',
      'people_i_ve_talked_to': 'నేను మాట్లాడిన వ్యక్తులు',
      'no_recent_memories_yet': 'ఇప్పటివరకు ఇటీవలి జ్ఞాపకాలు లేవు.',
      'scan_using_camera_icon': 'కెమెరా ఐకాన్‌తో స్కాన్ చేయండి',
      'ask_caregiver_to_save_profile': 'పేషెంట్ ప్రొఫైల్ సేవ్ చేయడానికి కేర్‌గివర్‌కు చెప్పండి',
      'unknown_person_detected': 'అజ్ఞాత వ్యక్తి కనబడినాడు',
      'patient_not_enrolled': 'పేషెంట్ నమోదు చేయబడలేదు. స్కాన్‌కి ముందు కేర్‌గివర్ ప్రొఫైల్ సేవ్ చేయాలి.',
      'patient_mode': 'పేషెంట్ మోడ్',
      'games': 'ఆటలు',
      'relationship': 'సంబంధం',
      'none': 'ఏదీ లేదు',
      'usage_reminder_title': 'వినియోగ రిమైండర్',
      'usage_reminder_message': 'మీరు ఈ అప్లికేషన్‌ను ఉపయోగిస్తున్నారు.',
      'recent_memories': 'ఇటీవలి జ్ఞాపకాలు',
      'conversation_capture_active': 'మాట్లాడటం రికార్డ్ అవుతోంది.',
      'glasses_recording': 'మీ అద్దాలు ఈ సంభాషణను రికార్డ్ చేస్తున్నాయి.',
      'last_conversation': 'చివరి సంభాషణ',
      'no_previous_conversation_found': 'మునుపటి సంభాషణ కనబడలేదు.',
      'start_conversation': 'సంభాషణ ప్రారంభించండి',
      'stop_recording': 'రికార్డింగ్ ఆపండి',
      'saving': 'సేవ్ చేస్తున్నాం...',
      'capturing_conversation': 'సంభాషణను రికార్డ్ చేస్తున్నాం...',
      'waiting_for_speech': 'మాట కోసం వేచి ఉన్నాం...',
      'listening': 'వినుగోంటున్నాం...',
      'language': 'భాష',
      'recognized': 'గుర్తించబడింది',
      'exit_patient_mode_question': 'పేషెంట్ మోడ్ నుండి వెళ్లాలా?',
      'exit_patient_mode_message': 'ఇది పేషెంట్ స్క్రీన్‌ను మూసివేసి కేర్‌గివర్ సైన్-ఇన్‌కు తిరిగి తీసుకెళుతుంది.',
      'cancel': 'రద్దు',
      'exit': 'నిష్క్రమించండి',
      'back_to_home': 'ఇంటికి తిరిగి వెళ్లండి',
      'try_again': 'దయచేసి మళ్లీ ప్రయత్నించండి.',
      'speaking_last_summary': 'చివరి సారాంశాన్ని మాట్లాడుతున్నాం...',
      'ready_to_capture': 'మీ సంభాషణను రికార్డ్ చేయడానికి సిద్దంగా ఉంది.',
      'starting_recording': 'రికార్డింగ్ ప్రారంభమవుతోంది...',
      'recording_not_started': 'రికార్డింగ్ ప్రారంభం కాలేదు.',
      'microphone_required': 'మీ సంభాషణను రికార్డ్ చేయడానికి మైక్రోఫోన్ అనుమతి అవసరం.',
      'no_speech_detected': '5 సెకన్లలో మాట కనబడలేదు. రికార్డింగ్ ఆపబడుతోంది...',
      'conversation_saved_success': 'సంభాషణ సేవ్ అయింది. ఇంటికి తిరుగుతోంది...',
      'conversation_save_failed': 'సంభాషణను సేవ్ చేయడంలో విఫలమైంది. మీరు ఇంటి నుండి మళ్లీ ప్రయత్నించవచ్చు.',
      'people_talked_to': 'నేను మాట్లాడిన వ్యక్తులు',
      'game_sequence_memory': 'క్రమ జ్ఞాపకం',
      'game_image_matching': 'చిత్రాల సరిపోలిక',
      'game_missing_card_memory': 'కనిపించని కార్డు జ్ఞాపకం',
      'game_daily_routine_recall': 'రోజువారీ పనుల జ్ఞాపకం',
      'routine_wake_up': 'నిద్రలేవడం',
      'routine_brush': 'పళ్లు తోమడం',
      'routine_breakfast': 'అల్పాహారం',
      'routine_medicine': 'మందు',
      'routine_walk': 'నడక',
      'routine_rest': 'విశ్రాంతి',
      'game_start': 'ప్రారంభించండి',
      'sequence_observe': 'ప్రతి సంఖ్య స్థానం గుర్తుంచుకోండి.\n1 నుంచి {number} వరకు క్రమంలో తెరవండి.',
      'sequence_find': '{number}ను కనుగొనండి',
      'sequence_completed': 'క్రమం పూర్తయింది!',
      'game_try_again': 'మళ్లీ ప్రయత్నించండి',
      'image_observe': 'కార్డుల స్థానాలు మరియు జతలను గుర్తుంచుకోండి.',
      'image_open_pair': 'ఒక కార్డును తెరిచి, తర్వాత మరొక కార్డును తెరవండి.',
      'image_match': 'జత కలిసింది!',
      'image_not_match': 'జత కాలేదు',
      'game_great_job': 'చాలా బాగా చేశారు!',
      'missing_observe': 'అన్ని కార్డులను గుర్తుంచుకోండి.\nఒక కార్డు కనిపించకుండా ఉంటుంది.',
      'missing_question': 'ఏ కార్డు కనిపించడం లేదు?',
      'game_correct': 'సరైనది!',
      'routine_observe': 'క్రింది రోజువారీ క్రమాన్ని జాగ్రత్తగా గమనించండి.',
      'routine_after': '{activity} తర్వాత ఏమి వస్తుంది?',
      'routine_before': '{activity} ముందు ఏమి వస్తుంది?',
      'routine_first': 'మొదటి పని ఏమిటి?',
      'routine_not_quite': 'సరైంది కాదు',
      'routine_next_question': 'తదుపరి ప్రశ్న',
      'game_unavailable': 'ఆట అందుబాటులో లేదు',
      'game_completed': 'ఆట పూర్తయింది',
      'game_label': 'ఆట: {game}',
      'accuracy_label': 'ఖచ్చితత్వం: {accuracy}%',
      'correct_attempts_label': 'సరైనవి: {correct}/{attempts} ప్రయత్నాలు',
      'errors_label': 'తప్పులు: {errors}',
      'attempts_label': 'ప్రయత్నాలు: {attempts}',
      'difficulty_label': 'కష్టం స్థాయి: {level}',
      'sending_result': 'ఫలితాన్ని కేర్‌గివర్‌కు పంపుతున్నాం...',
      'score_save_failed': 'ఫలితాన్ని పంపలేకపోయాం. కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
      'retry': 'మళ్లీ ప్రయత్నించండి',
      'result_sent': 'ఫలితం కేర్‌గివర్‌కు పంపబడింది.',
      'back_to_games': 'ఆటలకు తిరిగి వెళ్ళండి',
      'improvements_patient_title': 'రోగి పురోగతి',
      'improvements_load_error': 'ఆట ఫలితాలను లోడ్ చేయలేకపోయాం',
      'caregiver_sign_in_required': 'ఫలితాలను పొందడానికి కేర్‌గివర్ సైన్-ఇన్ అవసరం.',
      'improvements_performance': 'ఆట ప్రదర్శన',
      'improvements_history': 'ఆట చరిత్ర',
      'improvements_empty': 'ఇంకా ఆట ఫలితాలు లేవు.',
      'improvements_correct_total': 'సరైనవి {correct}/{total}',
      'improvements_played_times': '{count} సార్లు ఆడారు',
      'improvements_latest': 'తాజా {score}%',
      'session_expired': 'మీ సెషన్ గడువు ముగిసింది. దయచేసి మళ్లీ సైన్ ఇన్ చేయండి.',
    },
    'Tamil': {
      'checking_whos_here': 'இங்கு யார் இருக்கிறார்கள் என்று சரிபார்க்கிறோம்...',
      'no_face_detected': 'முகம் கண்டறியப்படவில்லை',
      'no_matching_patient_found': 'பொருந்தும் நோயாளர் இல்லை',
      'ready_to_scan': 'ஸ்கேன் செய்ய தயாராக உள்ளது',
      'people_i_ve_talked_to': 'நான் பேசியவர்கள்',
      'no_recent_memories_yet': 'இதுவரை சமீபத்திய நினைவுகள் இல்லை.',
      'scan_using_camera_icon': 'கேமரா ஐகானைப் பயன்படுத்தி ஸ்கேன் செய்யுங்கள்',
      'ask_caregiver_to_save_profile': 'நோயாளியின் சுயவிவரத்தை சேமிக்க பராமரிப்பாளரை கேளுங்கள்',
      'unknown_person_detected': 'அறிமுகமில்லாத நபர் கண்டறியப்பட்டார்',
      'patient_not_enrolled': 'நோயாளர் பதிவு செய்யப்படவில்லை. ஸ்கேன் செய்வதற்கு முன் பராமரிப்பாளர் சுயவிவரத்தை சேமிக்க வேண்டும்.',
      'patient_mode': 'நோயாளர் முறை',
      'games': 'விளையாட்டுகள்',
      'relationship': 'உறவு',
      'none': 'எதுவுமில்லை',
      'usage_reminder_title': 'பயன்பாட்டு நினைவூட்டல்',
      'usage_reminder_message': 'நீங்கள் இந்த பயன்பாட்டைப் பயன்படுத்துகிறீர்கள்.',
      'recent_memories': 'சமீபத்திய நினைவுகள்',
      'conversation_capture_active': 'உரையாடல் பதிவு செயலிலுள்ளது.',
      'glasses_recording': 'உங்கள் கண்ணாடிகள் இந்த உரையாடலை பதிவு செய்கின்றன.',
      'last_conversation': 'கடைசி உரையாடல்',
      'no_previous_conversation_found': 'முந்தைய உரையாடல் இல்லை.',
      'start_conversation': 'உரையாடலைத் தொடங்குங்கள்',
      'stop_recording': 'பதிவை நிறுத்து',
      'saving': 'சேமிக்கப்படுகிறது...',
      'capturing_conversation': 'உரையாடலை பதிவு செய்கின்றோம்...',
      'waiting_for_speech': 'பேச்சுக்காக காத்திருக்கிறோம்...',
      'listening': 'கேட்கிறோம்...',
      'language': 'மொழி',
      'recognized': 'அடையாளம் காணப்பட்டது',
      'exit_patient_mode_question': 'நோயாளர் முறையிலிருந்து வெளியேற வேண்டுமா?',
      'exit_patient_mode_message': 'இது நோயாளர் திரையை மூடி பராமரிப்பாளர் சைன்-இன் பக்கத்திற்குத் திருப்பி விடும்.',
      'cancel': 'ரத்து',
      'exit': 'வெளியேறு',
      'back_to_home': 'வீட்டிற்கு திரும்பு',
      'try_again': 'தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
      'speaking_last_summary': 'கடைசி சுருக்கத்தை பேசுகிறோம்...',
      'ready_to_capture': 'உங்கள் உரையாடலைப் பதிவுசெய்ய தயாராக உள்ளது.',
      'starting_recording': 'பதிவு தொடங்குகிறது...',
      'recording_not_started': 'பதிவு தொடங்கவில்லை.',
      'microphone_required': 'உங்கள் உரையாடலைப் பதிவுசெய்ய மைக்ரோஃபோன் அனுமதி தேவை.',
      'no_speech_detected': '5 விநாடிகளில் பேச்சு கண்டறியப்படவில்லை. பதிவு நிறுத்தப்படுகிறது...',
      'conversation_saved_success': 'உரையாடல் சேமிக்கப்பட்டது. வீட்டிற்கு திரும்புகிறது...',
      'conversation_save_failed': 'உரையாடலைச் சேமிக்க முடியவில்லை. வீட்டிலிருந்து மீண்டும் முயற்சி செய்யலாம்.',
      'people_talked_to': 'நான் பேசிக் கொண்டவர்கள்',
      'game_sequence_memory': 'வரிசை நினைவகம்',
      'game_image_matching': 'படப் பொருத்தம்',
      'game_missing_card_memory': 'காணாமல் போன அட்டை நினைவகம்',
      'game_daily_routine_recall': 'தினசரி நடைமுறை நினைவகம்',
      'routine_wake_up': 'எழுந்திருத்தல்',
      'routine_brush': 'பல் துலக்குதல்',
      'routine_breakfast': 'காலை உணவு',
      'routine_medicine': 'மருந்து',
      'routine_walk': 'நடைப்பயிற்சி',
      'routine_rest': 'ஓய்வு',
      'game_start': 'தொடங்கு',
      'sequence_observe': 'ஒவ்வொரு எண்ணின் இடத்தையும் நினைவில் கொள்ளுங்கள்.\n1 முதல் {number} வரை வரிசையாகத் திறக்கவும்.',
      'sequence_find': '{number}ஐக் கண்டுபிடிக்கவும்',
      'sequence_completed': 'வரிசை முடிந்தது!',
      'game_try_again': 'மீண்டும் முயற்சிக்கவும்',
      'image_observe': 'அட்டைகளின் இடங்களையும் பொருந்தும் ஜோடிகளையும் நினைவில் கொள்ளுங்கள்.',
      'image_open_pair': 'ஒரு அட்டையைத் திறந்து, பிறகு மற்றொன்றைத் திறக்கவும்.',
      'image_match': 'பொருந்தியது!',
      'image_not_match': 'பொருந்தவில்லை',
      'game_great_job': 'நன்றாகச் செய்தீர்கள்!',
      'missing_observe': 'அனைத்து அட்டைகளையும் நினைவில் கொள்ளுங்கள்.\nஒரு அட்டை மறைக்கப்படும்.',
      'missing_question': 'எந்த அட்டை காணவில்லை?',
      'game_correct': 'சரி!',
      'routine_observe': 'கீழே உள்ள நடைமுறையை கவனமாகப் பாருங்கள்.',
      'routine_after': '{activity}க்குப் பிறகு என்ன வரும்?',
      'routine_before': '{activity}க்கு முன் என்ன வரும்?',
      'routine_first': 'முதல் செயல் எது?',
      'routine_not_quite': 'சரியாக இல்லை',
      'routine_next_question': 'அடுத்த கேள்வி',
      'game_unavailable': 'விளையாட்டு கிடைக்கவில்லை',
      'game_completed': 'விளையாட்டு முடிந்தது',
      'game_label': 'விளையாட்டு: {game}',
      'accuracy_label': 'துல்லியம்: {accuracy}%',
      'correct_attempts_label': 'சரி: {correct}/{attempts} முயற்சிகள்',
      'errors_label': 'தவறுகள்: {errors}',
      'attempts_label': 'முயற்சிகள்: {attempts}',
      'difficulty_label': 'சிரம நிலை: {level}',
      'sending_result': 'முடிவை பராமரிப்பாளருக்கு அனுப்புகிறது...',
      'score_save_failed': 'முடிவை அனுப்ப முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      'result_sent': 'முடிவு பராமரிப்பாளருக்கு அனுப்பப்பட்டது.',
      'back_to_games': 'விளையாட்டுகளுக்குத் திரும்பு',
      'improvements_patient_title': 'நோயாளர் முன்னேற்றம்',
      'improvements_load_error': 'விளையாட்டு முடிவுகளை ஏற்ற முடியவில்லை',
      'caregiver_sign_in_required': 'முடிவுகளைப் பெற பராமரிப்பாளர் உள்நுழைய வேண்டும்.',
      'improvements_performance': 'விளையாட்டு செயல்திறன்',
      'improvements_history': 'விளையாட்டு வரலாறு',
      'improvements_empty': 'இதுவரை விளையாட்டு முடிவுகள் இல்லை.',
      'improvements_correct_total': 'சரி {correct}/{total}',
      'improvements_played_times': '{count} முறை விளையாடப்பட்டது',
      'improvements_latest': 'சமீபத்தியது {score}%',
      'session_expired': 'உங்கள் அமர்வு முடிந்துவிட்டது. மீண்டும் சைன் இன் செய்யவும்.',
    },
    'Hindi': {
      'checking_whos_here': 'यहाँ कौन है देख रहे हैं...',
      'no_face_detected': 'चेहरा नहीं मिला',
      'no_matching_patient_found': 'मिलान करने वाला रोगी नहीं मिला',
      'ready_to_scan': 'स्कैन के लिए तैयार',
      'people_i_ve_talked_to': 'मैंने जिनसे बात की',
      'no_recent_memories_yet': 'अभी तक कोई हाल की यादें नहीं हैं।',
      'scan_using_camera_icon': 'कैमरा आइकन से स्कैन करें',
      'ask_caregiver_to_save_profile': 'रोगी का प्रोफ़ाइल सेव करने के लिए देखभालकर्ता से कहें',
      'unknown_person_detected': 'अजनबी व्यक्ति पाया गया',
      'patient_not_enrolled': 'रोगी पंजीकृत नहीं है। स्कैन से पहले देखभालकर्ता प्रोफ़ाइल सेव करेगा।',
      'patient_mode': 'रोगी मोड',
      'games': 'खेल',
      'relationship': 'रिश्ता',
      'none': 'कोई नहीं',
      'usage_reminder_title': 'उपयोग अनुस्मारक',
      'usage_reminder_message': 'आप इस ऐप्लिकेशन का उपयोग कर रहे हैं।',
      'recent_memories': 'हाल की यादें',
      'conversation_capture_active': 'बातचीत रिकॉर्डिंग सक्रिय है।',
      'glasses_recording': 'आपके चश्मे यह बातचीत रिकॉर्ड कर रहे हैं।',
      'last_conversation': 'अंतिम बातचीत',
      'no_previous_conversation_found': 'पिछली बातचीत नहीं मिली।',
      'start_conversation': 'बातचीत शुरू करें',
      'stop_recording': 'रिकॉर्डिंग रोकें',
      'saving': 'सेव हो रहा है...',
      'capturing_conversation': 'बातचीत रिकॉर्ड की जा रही है...',
      'waiting_for_speech': 'भाषण की प्रतीक्षा...',
      'listening': 'सुन रहे हैं...',
      'language': 'भाषा',
      'recognized': 'पहचाना गया',
      'exit_patient_mode_question': 'रोगी मोड से बाहर निकलें?',
      'exit_patient_mode_message': 'यह रोगी स्क्रीन बंद कर देगा और देखभालकर्ता साइन-इन पर लौटाएगा।',
      'cancel': 'रद्द करें',
      'exit': 'बाहर निकलें',
      'back_to_home': 'होम पर वापस जाएँ',
      'try_again': 'कृपया फिर से प्रयास करें।',
      'speaking_last_summary': 'अंतिम सारांश पढ़ा जा रहा है...',
      'ready_to_capture': 'आपकी बातचीत रिकॉर्ड करने के लिए तैयार है।',
      'starting_recording': 'रिकॉर्डिंग शुरू हो रही है...',
      'recording_not_started': 'रिकॉर्डिंग शुरू नहीं हुई।',
      'microphone_required': 'आपकी बातचीत रिकॉर्ड करने के लिए माइक्रोफोन अनुमति आवश्यक है।',
      'no_speech_detected': '5 सेकंड में बोल नहीं मिला। रिकॉर्डिंग रोक रही है...',
      'conversation_saved_success': 'बातचीत सेव हो गई। होम पर लौट रहे हैं...',
      'conversation_save_failed': 'बातचीत सेव नहीं हुई। आप घर से फिर से कोशिश कर सकते हैं।',
      'people_talked_to': 'मैंने जिनसे बात की',
      'game_sequence_memory': 'क्रम स्मृति',
      'game_image_matching': 'चित्र मिलान',
      'game_missing_card_memory': 'लापता कार्ड स्मृति',
      'game_daily_routine_recall': 'दैनिक दिनचर्या स्मरण',
      'routine_wake_up': 'जागना',
      'routine_brush': 'ब्रश करना',
      'routine_breakfast': 'नाश्ता',
      'routine_medicine': 'दवा',
      'routine_walk': 'टहलना',
      'routine_rest': 'आराम',
      'game_start': 'शुरू करें',
      'sequence_observe': 'हर संख्या की जगह याद रखें।\n1 से {number} तक क्रम में खोलें।',
      'sequence_find': '{number} ढूँढें',
      'sequence_completed': 'क्रम पूरा हुआ!',
      'game_try_again': 'फिर से कोशिश करें',
      'image_observe': 'कार्डों की जगह और मेल खाने वाली जोड़ियाँ याद रखें।',
      'image_open_pair': 'एक कार्ड खोलें, फिर दूसरा कार्ड खोलें।',
      'image_match': 'मिलान हुआ!',
      'image_not_match': 'मिलान नहीं हुआ',
      'game_great_job': 'बहुत अच्छा!',
      'missing_observe': 'सभी कार्ड याद रखें।\nएक कार्ड गायब होगा।',
      'missing_question': 'कौन सा कार्ड गायब है?',
      'game_correct': 'सही!',
      'routine_observe': 'नीचे दी गई दिनचर्या को ध्यान से देखें।',
      'routine_after': '{activity} के बाद क्या आता है?',
      'routine_before': '{activity} से पहले क्या आता है?',
      'routine_first': 'पहली गतिविधि क्या है?',
      'routine_not_quite': 'सही नहीं',
      'routine_next_question': 'अगला प्रश्न',
      'game_unavailable': 'खेल उपलब्ध नहीं है',
      'game_completed': 'खेल पूरा हुआ',
      'game_label': 'खेल: {game}',
      'accuracy_label': 'सटीकता: {accuracy}%',
      'correct_attempts_label': 'सही: {correct}/{attempts} प्रयास',
      'errors_label': 'गलतियाँ: {errors}',
      'attempts_label': 'प्रयास: {attempts}',
      'difficulty_label': 'कठिनाई स्तर: {level}',
      'sending_result': 'परिणाम देखभालकर्ता को भेजा जा रहा है...',
      'score_save_failed': 'परिणाम नहीं भेजा जा सका। कनेक्शन जाँचकर फिर कोशिश करें।',
      'retry': 'फिर कोशिश करें',
      'result_sent': 'परिणाम देखभालकर्ता को भेज दिया गया।',
      'back_to_games': 'खेलों पर वापस जाएँ',
      'improvements_patient_title': 'रोगी की प्रगति',
      'improvements_load_error': 'खेल के परिणाम लोड नहीं हो सके',
      'caregiver_sign_in_required': 'परिणाम देखने के लिए देखभालकर्ता को साइन इन करना होगा।',
      'improvements_performance': 'खेल प्रदर्शन',
      'improvements_history': 'खेल इतिहास',
      'improvements_empty': 'अभी तक कोई खेल परिणाम दर्ज नहीं है।',
      'improvements_correct_total': 'सही {correct}/{total}',
      'improvements_played_times': '{count} बार खेला',
      'improvements_latest': 'नवीनतम {score}%',
      'session_expired': 'आपका सत्र समाप्त हो गया है। कृपया फिर से साइन इन करें।',
    },
  };
}
