# Generated by Django 6.0.7 on 2026-07-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '__first__'),
        ('patients', '0002_patient_fcm_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('patient', 'Patient'), ('known_person', 'Known Person')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('encoding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('face_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encoding', to='patients.faceimage')),
            ],
        ),
    ]
