# Generated by Django 6.0.7 on 2026-07-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('known_people', '0001_initial'),
        ('patients', '0002_patient_fcm_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='known_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_history', to='known_people.knownperson'),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_history', to='patients.patient'),
        ),
    ]
