# Generated by Django 6.0.7 on 2026-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='conversation_audio/'),
        ),
    ]
