# Generated by Django 6.0.7 on 2026-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversationhistory_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='content_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='localized_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
