# Generated by Django 6.0.7 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversationhistory_content_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_captures/'),
        ),
    ]
