# Generated by Django 6.0.7 on 2026-07-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '__first__'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(blank=True, choices=[('patient', 'Patient'), ('known_person', 'Known Person')], max_length=20, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(max_length=50)),
                ('outcome', models.CharField(choices=[('matched', 'Matched'), ('not_matched', 'Not Matched'), ('breach_alert', 'Breach Alert')], max_length=20)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_history', to='patients.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
