# Generated by Django 6.0.7 on 2026-07-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionhistory',
            name='outcome',
            field=models.CharField(choices=[('matched', 'Matched'), ('not_matched', 'Not Matched'), ('breach_alert', 'Breach Alert'), ('known_person_push', 'Known Person Push')], max_length=20),
        ),
    ]
