# Generated by Django 6.0.7 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_recognitionhistory_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionhistory',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='recognition_captures/'),
        ),
    ]
