# Generated by Django 6.0.7 on 2026-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationping',
            name='distance_from_center_meters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
