# Generated by Django 6.0.7 on 2026-07-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fcm_device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
